### ISSUE TITLE
[Documentation] missing upgrade notes from 10.x to 11.x

### ISSUE THREAD

**Issue by marcocarvalho** [Bandwidth/ruby-sdk#117]
### Description

Hi, the SDK structure in 10.5.0 is completely different from 11.x.x can you provide upgrade notes to ease the upgrade? There a lot of breaking changes.

cc @ckoegel  about https://github.com/Bandwidth/ruby-sdk/pull/61

**Comment by ajrice6713** [comment]
Hey @marcocarvalho - we have a migration guide available [here](https://dev.bandwidth.com/migration-guides/ruby/v10-to-v11/)

**Comment by marcocarvalho** [comment]
@ajrice6713 Thanks!
