### ISSUE TITLE
Error updating from 4.0.0 to 6.0.0

### ISSUE THREAD

**Issue by raivil** [Bandwidth/ruby-sdk#14]
Hey,

I've updated the gem from `4.0.0` to `6.0.0` and I can't create sms anymore.

Code to create SMS is similar to the example at https://github.com/Bandwidth/ruby-sdk#send-text-message

```
    bandwidth_message = Bandwidth::MessageRequest.new
    bandwidth_message.application_id = "abc-123"
    bandwidth_message.to = to_number
    bandwidth_message.from = from_number
    bandwidth_message.tag = message.id
    bandwidth_message.text = body

    client.create_message(account_id, body: bandwidth_message)
```

Error message:
```
"Unrecognized JSON property: 'body' near line 1, column 10"
```

Any idea what is going on?

**Comment by ajrice6713** [comment]
Hey Raivii,

Thank you for bringing this to our attention - it looks like a bug in the JSON generation, the object is double nested within two 'body' tags - we are working on a fix and will release 6.0.1 shortly

**Comment by jmulford-bw** [comment]
Hey @raivil,

This actually is a result of us changing the OpenAPI definitions to be more accurate. The sdk is "correct" but the docs slipped by and weren't updated. This should be fixable by changing your request to look like `client.create_message(account_id, bandwidth_message)`. We'll update the readme and docs to reflect this

Please let us know if there are any other issues, my apologies for this

**Comment by raivil** [comment]
@jmulford-bw does it affect only SMS or do I need to update voice messaging related code too?
Replace 
```
client.create_call(account_id, body: bandwidth_message)
```
with 
```
client.create_call(account_id, bandwidth_message)
```

**Comment by jmulford-bw** [comment]
Just SMS right now, the voice spec didn't get updated and the `create_call` definition should remain as is

**Comment by jmulford-bw** [comment]
We'll have another major update that changes that in the future and will make sure to communicate the change properly
