### ISSUE TITLE
Old account related data

### ISSUE THREAD

**Issue by eftikharEmad** [Bandwidth/ruby-sdk#2]
Hello Team, 

this is not an issue by it self but it is something I can't do it and I need help.
we were using [bandwidth v1](https://github.com/Bandwidth/ruby-bandwidth), so we had numbers, calls and related records.
after migrating to [bandwidth v2](https://github.com/Bandwidth/ruby-sdk), numbers were migrated but I am not sure about the records, where I can find the old records or better How !!?

Thank you.

**Comment by AlexDWu** [comment]
It seems numbers are managed by https://github.com/Bandwidth/ruby-bandwidth-iris now.

**Comment by eftikharEmad** [comment]
Thank you @AlexDWu for answering.
we already contact the bandwidth team about migrating data from old to the new account, but it seems I didn't close this issue
